# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

# Blog to build multiarch images with GH, docker buildx and manifests
# https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/

# Setup Multiarch builds with docker and QEMU, restart docker service!
# https://github.com/docker/buildx#building-multi-platform-images
version: 2
builds:
  - env:
      - CGO_ENABLED=0 # this is needed to build the single binary
    goarch:
      - amd64
      - arm64
    goos:
      - linux

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
  - image_templates:
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-amd64"

    extra_files:
      - docker/zfs.sh
      - docker/update-permissions.sh
    goarch: amd64
    dockerfile: docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-arm64"

    extra_files:
      - docker/zfs.sh
      - docker/update-permissions.sh
    goarch: arm64
    dockerfile: docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  # For prereleases, updating `latest` and the floating tags of the major version does not make sense.
  # Only the image for the exact version should be pushed.

  - name_template: "{{ if not .Prerelease }}ghcr.io/tosih/zfs-provisioner:latest{{ end }}"
    image_templates:
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-amd64"
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-arm64"

  - name_template: "{{ if not .Prerelease }}ghcr.io/tosih/zfs-provisioner:v{{ .Major }}{{ end }}"
    image_templates:
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-amd64"
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-arm64"

  - name_template: "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}"
    image_templates:
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-amd64"
      - "ghcr.io/tosih/zfs-provisioner:v{{ .Version }}-arm64"

release:
  prerelease: auto
  github:
    owner: tosih
    name: kubernetes-zfs-provisioner
